<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- This is the GNU Emacs Lisp Reference Manual
corresponding to Emacs version 25.1.

Copyright (C) 1990-1996, 1998-2016 Free Software Foundation, Inc.

Permission is granted to copy, distribute and/or modify this document under
the terms of the GNU Free Documentation License, Version 1.3 or any later
version published by the Free Software Foundation; with the Invariant
Sections being "GNU General Public License," with the Front-Cover Texts
being "A GNU Manual," and with the Back-Cover Texts as in (a) below.  A
copy of the license is included in the section entitled "GNU Free
Documentation License."

(a) The FSF's Back-Cover Text is: "You have the freedom to copy and modify
this GNU manual.  Buying copies from the FSF supports it in developing GNU
and promoting software freedom." -->
<!-- Created by GNU Texinfo 6.6, http://www.gnu.org/software/texinfo/ -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>10.6.2 catchとthrownの例 (GNU Emacs Lisp Reference Manual)</title>

<meta name="description" content="10.6.2 catchとthrownの例 (GNU Emacs Lisp Reference Manual)">
<meta name="keywords" content="10.6.2 catchとthrownの例 (GNU Emacs Lisp Reference Manual)">
<meta name="resource-type" content="document">
<meta name="distribution" content="global">
<meta name="Generator" content="makeinfo">
<link href="index.html#Top" rel="start" title="Emacs Lisp">
<link href="Index.html#Index" rel="index" title="Index">
<link href="index.html#SEC_Contents" rel="contents" title="Table of Contents">
<link href="Nonlocal-Exits.html#Nonlocal-Exits" rel="up" title="10.6 非ローカル脱出">
<link href="Errors.html#Errors" rel="next" title="10.6.3 エラー">
<link href="Catch-and-Throw.html#Catch-and-Throw" rel="prev" title="10.6.1 明示的な非ローカル脱出: catchとthrow">
<style type="text/css">
<!--
a.summary-letter {text-decoration: none}
blockquote.indentedblock {margin-right: 0em}
div.display {margin-left: 3.2em}
div.example {margin-left: 3.2em}
div.lisp {margin-left: 3.2em}
kbd {font-style: oblique}
pre.display {font-family: inherit}
pre.format {font-family: inherit}
pre.menu-comment {font-family: serif}
pre.menu-preformatted {font-family: serif}
span.nolinebreak {white-space: nowrap}
span.roman {font-family: initial; font-weight: normal}
span.sansserif {font-family: sans-serif; font-weight: normal}
ul.no-bullet {list-style: none}
-->
</style>


</head>

<body lang="en">
<span id="Examples-of-Catch"></span><div class="header">
<p>
Next: <a href="Errors.html#Errors" accesskey="n" rel="next">Errors</a>, Previous: <a href="Catch-and-Throw.html#Catch-and-Throw" accesskey="p" rel="prev">Catch and Throw</a>, Up: <a href="Nonlocal-Exits.html#Nonlocal-Exits" accesskey="u" rel="up">Nonlocal Exits</a> &nbsp; [<a href="index.html#SEC_Contents" title="Table of contents" rel="contents">Contents</a>][<a href="Index.html#Index" title="Index" rel="index">Index</a>]</p>
</div>
<hr>
<span id="catchtothrownnoLi"></span><h4 class="subsection">10.6.2 <code>catch</code>と<code>thrown</code>の例</h4>

<p>2重にネストされたループから脱出する1つの方法は、<code>catch</code>と<code>throw</code>を使うことです(これはほとんどの言語では<code>goto</code>により行なわれるだろう)。ここでは<var>i</var>と<var>j</var>を0から9に変化させて、<code>(foo
<var>i</var> <var>j</var>)</code>を計算します:
</p>
<div class="example">
<pre class="example">(defun search-foo ()
  (catch 'loop
    (let ((i 0))
      (while (&lt; i 10)
        (let ((j 0))
          (while (&lt; j 10)
            (if (foo i j)
                (throw 'loop (list i j)))
            (setq j (1+ j))))
        (setq i (1+ i))))))
</pre></div>

<p><code>foo</code>が非<code>nil</code>をリターンしたら即座に処理を中止して、<var>i</var>と<var>j</var>のリストをリターンしています。<code>foo</code>が常に<code>nil</code>をリターンする場合には、<code>catch</code>は通常どおりリターンして、その値は<code>while</code>の結果である<code>nil</code>となります。
</p>
<p>以下では2つのリターン位置を一度に表す、微妙に異なるトリッキーな例を2つ示します。まず同じタグ<code>hack</code>にたいして2つのリターン位置があります:
</p>
<div class="example">
<pre class="example">(defun catch2 (tag)
  (catch tag
    (throw 'hack 'yes)))
&rArr; catch2
</pre><pre class="example">

</pre><pre class="example">(catch 'hack
  (print (catch2 'hack))
  'no)
-| yes
&rArr; no
</pre></div>

<p>どちらのリターン位置も<code>throw</code>にマッチするタグをもつので内側のもの、つまり<code>catch2</code>で確立されたcatchへgotoします。したがって<code>catch2</code>は通常どおり値<code>yes</code>をリターンして、その値がプリントされます。最後に外側の<code>catch</code>の2番目のbody、つまり<code>'no</code>が評価されて外側の<code>catch</code>からそれがリターンされます。
</p>
<p>ここで<code>catch2</code>に与える引数を変更してみましょう:
</p>
<div class="example">
<pre class="example">(catch 'hack
  (print (catch2 'quux))
  'no)
&rArr; yes
</pre></div>

<p>この場合も2つのリターン位置がありますが、今回は外側だけがタグ<code>hack</code>で、内側はかわりにタグ<code>quux</code>をもちます。したがって<code>throw</code>により、外側の<code>catch</code>が値<code>yes</code>をリターンします。関数<code>print</code>が呼び出されることはなくbodyのフォーム<code>'no</code>も決して評価されません。
</p>



</body>
</html>
